# Generated by Django 3.1.6 on 2021-02-26 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('job_desc', models.CharField(max_length=3000)),
                ('min_salary', models.IntegerField(blank=True)),
                ('max_salary', models.IntegerField(blank=True)),
                ('requirements', models.CharField(max_length=2000)),
                ('expire_date', models.DateField()),
                ('salary_type', models.CharField(blank=True, choices=[('USD', 'USD'), ('EUR', 'EUR'), ('PLN', 'PLN')], default='PLN', max_length=100)),
                ('contract_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Concract', 'Concract')], default='Full Time', max_length=100)),
                ('experience_type', models.CharField(choices=[('Trainee', 'Trainee'), ('Junior', 'Junior'), ('Regular', 'Regular'), ('Senior', 'Senior'), ('Expert', 'Expert')], default='Regular', max_length=100)),
                ('area_type', models.CharField(choices=[('IT', 'IT'), ('Tax', 'Tax'), ('Law', 'Law'), ('Accounting', 'Accounting'), ('Design', 'Design'), ('Video', 'Video'), ('Marketing', 'Marketing')], default='IT', max_length=100)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
