# Generated by Django 3.1.6 on 2021-02-26 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='expire_date',
        ),
    ]
