# Generated by Django 3.1.6 on 2021-02-26 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_form', '0002_remove_offer_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='max_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='min_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='salary_type',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('EUR', 'EUR'), ('PLN', 'PLN')], default='PLN', max_length=100, null=True),
        ),
    ]
