# Generated by Django 3.1.6 on 2021-02-26 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_form', '0003_auto_20210226_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='contract_type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Contract', 'Contract')], default='Full Time', max_length=100),
        ),
    ]
