# Generated by Django 3.1.6 on 2021-02-26 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_company', '0002_auto_20210226_0529'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_form', '0004_auto_20210226_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='company_data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_info', to='job_company.company'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_offer', to=settings.AUTH_USER_MODEL),
        ),
    ]
