# Generated by Django 3.1.6 on 2021-02-27 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_form', '0005_auto_20210226_0529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='company_data',
        ),
    ]
