# Generated by Django 3.1.6 on 2021-03-03 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_form', '0013_auto_20210303_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='name_company',
        ),
    ]
