# Generated by Django 3.1.6 on 2021-03-03 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_company', '0007_auto_20210303_1922'),
        ('job_form', '0015_offer_name_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='name_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_company.company'),
        ),
    ]
