# Generated by Django 3.1.6 on 2021-03-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_company', '0007_auto_20210303_1922'),
        ('job_form', '0016_auto_20210303_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='name_company',
        ),
        migrations.AddField(
            model_name='offer',
            name='name_company',
            field=models.ManyToManyField(to='job_company.Company'),
        ),
    ]
