# Generated by Django 3.1.6 on 2021-03-04 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_form', '0017_auto_20210304_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='name_company',
        ),
    ]
