# Generated by Django 3.1.6 on 2021-02-26 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('adress_city', models.CharField(max_length=200)),
                ('adress_street', models.CharField(max_length=300)),
                ('adress_street_nmb', models.IntegerField()),
                ('adress_flat_nmb', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
