# Generated by Django 3.1.6 on 2021-02-26 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='user',
            new_name='company',
        ),
    ]
