# Generated by Django 3.1.6 on 2021-02-26 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_company', '0002_auto_20210226_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='bio',
            field=models.CharField(default='Company info', max_length=1000),
        ),
        migrations.AlterField(
            model_name='company',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_information', to=settings.AUTH_USER_MODEL),
        ),
    ]
