# Generated by Django 3.1.6 on 2021-02-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_company', '0003_auto_20210226_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='bio',
            field=models.CharField(default='Company bio', max_length=1000),
        ),
    ]
