# Generated by Django 3.1.6 on 2021-02-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_company', '0004_auto_20210227_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='adress_city',
        ),
        migrations.RemoveField(
            model_name='company',
            name='adress_flat_nmb',
        ),
        migrations.RemoveField(
            model_name='company',
            name='adress_street',
        ),
        migrations.RemoveField(
            model_name='company',
            name='adress_street_nmb',
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='company',
            name='company_name',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='company',
            name='company_size',
            field=models.CharField(blank=True, choices=[('1-10', '1-10'), ('11-50', '11-50'), ('51-250', '51-250'), ('250+', '250+')], default='1-10', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(default='', max_length=200),
        ),
    ]
