# Generated by Django 3.1.6 on 2021-03-01 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_company', '0005_auto_20210227_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company',
            new_name='user',
        ),
    ]
