# Generated by Django 3.1.6 on 2021-03-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_company', '0006_auto_20210301_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='bio',
            field=models.TextField(default='Company bio', max_length=1000),
        ),
    ]
