# Generated by Django 3.1.6 on 2021-03-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_company', '0007_auto_20210303_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, default='kebab.jpg', null=True, upload_to=''),
        ),
    ]
