# Generated by Django 3.1.6 on 2021-03-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_company', '0008_auto_20210311_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(default='default_logo.png', upload_to=''),
        ),
    ]
